In [2]:
import numpy as np
import pandas as pd
print("Pandas version:",pd.__version__)
print("Numpy version:",np.__version__)

Pandas version: 2.3.3
Numpy version: 2.3.5

In [1]:
import pyodbc
#Connection
c = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=DESKTOP-8HDLIIL\SQLEXPRESS;"
    "DATABASE=master;"
    "Trusted_Connection=yes;"
)
print("Connected successfully!")

Connected successfully!

In [3]:
#File loading
df = pd.read_excel("Online Retail.xlsx")
print("Loaded successfully")

Loaded successfully

In [ ]:
#Market Analysis

In [4]:
#Revenue
df["Revenue"]=df["Quantity"]*df["UnitPrice"]

In [6]:
#1.Which 5 countries generate the highest revenue?
result=df.groupby("Country")["Revenue"].sum()
result.sort_values(ascending=False).head()

Country
United Kingdom    8187806.364
Netherlands        284661.540
EIRE               263276.820
Germany            221698.210
France             197403.900
Name: Revenue, dtype: float64

In [13]:
#2.Which 5 countries have the highest number of orders?
result=df.groupby("Country")["InvoiceNo"].nunique()
result.sort_values(ascending=False).head()

Country
United Kingdom    23494
Germany             603
France              461
EIRE                360
Belgium             119
Name: InvoiceNo, dtype: int64

In [ ]:
#Product Analysis

In [25]:
#High Revenue but Low Quantity
result=df.groupby("StockCode").agg(
    total_revenue=("Revenue","sum"),
    total_quantity=("Quantity","sum")
)
high_revenue=result["total_revenue"]>result["total_revenue"].median()
low_quantity=result["total_quantity"]<result["total_quantity"].median()
result[high_revenue&low_quantity].sort_values("total_quantity",ascending=False).head(10)

           total_revenue  total_quantity
StockCode
84884A           1197.96             300
22848            5048.95             300
22180            3366.69             300
84880            1972.64             300
84659A            673.72             298
23067            1249.11             297
23402            1151.03             297
23516            1062.35             297
22283            2710.53             297
23054            2613.18             296

In [6]:
#Top 10 Products by Revenue
r=df.groupby("StockCode")["Revenue"].sum()
r.sort_values(ascending=False).head(10)

StockCode
DOT       206245.48
22423     164762.19
47566      98302.98
85123A     97894.50
85099B     92356.03
23084      66756.59
POST       66230.64
22086      63791.94
84879      58959.73
79321      53768.06
Name: Revenue, dtype: float64

In [8]:
#Top 10 Products by Quantity Sold
r=df.groupby("StockCode")["Quantity"].sum()
r.sort_values(ascending=False).head(10)

StockCode
22197     56450
84077     53847
85099B    47363
85123A    38830
84879     36221
21212     36039
23084     30646
22492     26437
22616     26315
21977     24753
Name: Quantity, dtype: int64

In [17]:
#Are the products that sell the most units also the products that generate the most revenue?
result=df.groupby("StockCode").agg(
    total_revenue=("Revenue","sum"),
    total_quantity=("Quantity","sum")
)
result.sort_values("total_revenue",ascending=False).head(10)

           total_revenue  total_quantity
StockCode
DOT            206245.48            1707
22423          164762.19           12980
47566           98302.98           18022
85123A          97894.50           38830
85099B          92356.03           47363
23084           66756.59           30646
POST            66230.64            6353
22086           63791.94           18902
84879           58959.73           36221
79321           53768.06           10343

In [20]:
total_quantity=df["Quantity"].sum()
total_revenue=df["Revenue"].sum()

In [ ]:
#Revenue vs Quantity

In [22]:
#Products with high quantity but low revenue
result=df.groupby("StockCode").agg(
    total_revenue=("Revenue","sum"),
    total_quantity=("Quantity","sum")
)
high_quantity=result["total_quantity"]>result["total_quantity"].median()
low_revenue=result["total_revenue"]<result["total_revenue"].median()
result[high_quantity&low_revenue].sort_values("total_quantity",ascending=False).head(10)

           total_revenue  total_quantity
StockCode
84826             340.93           13645
37413             284.49            6271
16045             380.00            4333
16218             283.31            3821
16216             234.00            3333
M              -68674.19            3164
18007             395.61            3050
16219             404.84            3000
79063D             35.33            2750
17096             455.98            2497

In [23]:
#High Revenue but Low Quantity
result=df.groupby("StockCode").agg(
    total_revenue=("Revenue","sum"),
    total_quantity=("Quantity","sum")
)
high_revenue=result["total_revenue"]>result["total_revenue"].median()
low_quantity=result["total_quantity"]<result["total_quantity"].median()
result[high_revenue&low_quantity].sort_values("total_quantity",ascending=False).head(10)

           total_revenue  total_quantity
StockCode
84884A           1197.96             300
22848            5048.95             300
22180            3366.69             300
84880            1972.64             300
84659A            673.72             298
23067            1249.11             297
23402            1151.03             297
23516            1062.35             297
22283            2710.53             297
23054            2613.18             296